spring.application.name=urbanease

# Profile Configuration
spring.profiles.active=dev

# Enable Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Server Configuration
server.port=5025
server.servlet.context-path=/urbanease
# JWT Configuration
jwt.secret=675c13837c89be397468526619cc779373410f3fde3387722c0a04cd4fc95ef0
jwt.expiration=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME:your-email@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:your-app-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# OneSignal Configuration
onesignal.app.id=45e8defd-7643-4918-b5a1-bc76bbbebaad
onesignal.api.key=os_v2_app_ixun57lwinerrnnbxr3lxpv2vwy33vtx7fkev54766x7bogmjkl7iupy7dk66madj4m3juntyodhxksl7ypdfqk4fvf46uevb6y5l6q
onesignal.api.url=https://onesignal.com/api/v1/notifications
